### ISSUE TITLE
Broken Example

### ISSUE THREAD

**Issue by jpdevries** [uploadcare/uploadcare-redactor#1]
__console errors on example.html__  

 - Download the repo to a webserver
 - hit example.html
 - Notice errors

```
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (redactor.css, line 0)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (redactor.js, line 0)
[Error] TypeError: undefined is not a function (evaluating '$('#redactor').redactor')
	(anonymous function) (index.html, line 11)
	j (jquery.min.js, line 2)
	fireWith (jquery.min.js, line 2)
	ready (jquery.min.js, line 2)
	I (jquery.min.js, line 2)
```

![](http://j4p.us/image/2Y2f2Z3N123a/Screen%20Shot%202015-04-21%20at%201.46.52%20PM.png)

**Comment by jpdevries** [comment]
Oh duh. After copying over redactor.css and redactor.js works as expected. I suppose those wouldn't be included in a public repo :smile:

**Comment by dmitry-mukhin** [comment]
Hi.
You can just replace those with paths to your redactor.js and redactor.css. I don't think we have rights to distribute those.

**Comment by dmitry-mukhin** [comment]
Although, I understand that this can be confusing. Let's open it and address this in docs or something.

Thanks!

**Comment by jpdevries** [comment]
Makes sense. Sorry for the confusion.
