### ISSUE TITLE
Redactor X support

### ISSUE THREAD

**Issue by karelvasicek** [uploadcare/uploadcare-redactor#34]
We created an extension of this library and added support for Redactor X. Should we create a PR so this library would support v2, v3 and Redactor X or would it make sense to create separate repository for Redactor X?

**Comment by dmitry-mukhin** [comment]
if support can be added without breaking current lib, sure, send a PR

**Comment by karelvasicek** [comment]
It should be an extension of original lib w/o any breaking changes. PR is created.
