### ISSUE TITLE
Modal is not showing when the image is clicked in the Click-To-Edit

### ISSUE THREAD

**Issue by senior-engineer** [uploadcare/uploadcare-redactor#8]
I have uploaded one image and it is in the redactor widget now.(I am using Click-To-Edit mode) 
But the modal is not showing when the image is clicked inside the redactor widget and it works only when the out side of the image is clicked on the redactor editor. 
Anybody knows why?

**Comment by dmitry-mukhin** [comment]
currently, the widget is used to [insert](https://github.com/uploadcare/uploadcare-redactor/blob/master/uploadcare.js#L54-L57) an image (or a file).
you may remove inserted files as any other and upload and insert a new one.

changing (cropping etc.) of already uploaded images will be added in future versions.

**Comment by senior-engineer** [comment]
I don't understand what you mean. 
So when the redactor widget goes to edit mode, the already inserted image should be removed?

**Comment by dmitry-mukhin** [comment]
No they should not.
But the widget does not do any magic, it just inserts an image (or file) URL to the text.

Why do you want to "show the widget when you click on image"?

**Comment by senior-engineer** [comment]
As like the example of uploadcare-redactor plugin...

**Comment by dmitry-mukhin** [comment]
I don't understand :(

**Comment by senior-engineer** [comment]
In the example of the uploadcare-redactor plugin, if you upload image and then click the uploaded image again, the it shows the modal...

**Comment by dmitry-mukhin** [comment]
let's move the discussion to email please

**Comment by senior-engineer** [comment]
Which email should we use?

**Comment by dmitry-mukhin** [comment]
help@uploadcare.com
